//
//  CardsPresenter.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/3/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardsPresentationLogic
{
  func presentSomething(response: Cards.Something.Response)
}

class CardsPresenter: CardsPresentationLogic
{
  weak var viewController: CardsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Cards.Something.Response)
  {
    let viewModel = Cards.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
