//
//  StudyDeckInteractor.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/24/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StudyDeckBusinessLogic
{
    
}

protocol StudyDeckDataStore
{
  //var name: String { get set }
}

class ReviewDeckInteractor: StudyDeckBusinessLogic, StudyDeckDataStore
{
  var presenter: StudyDeckPresentationLogic?
  
  
  // MARK: Do something
  
}
