//
//  ExpandedCardDetailPresenter.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 7/20/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExpandedCardDetailPresentationLogic {
    func dismissVC(response: ExpandedCardDetail.DismissVC.Response)
}

class ExpandedCardDetailPresenter: ExpandedCardDetailPresentationLogic {
    
    weak var viewController: ExpandedCardDetailDisplayLogic?
    
    func dismissVC(response: ExpandedCardDetail.DismissVC.Response) {
        let viewModel = ExpandedCardDetail.DismissVC.ViewModel()
        viewController?.dismissVC(viewModel: viewModel)
    }
}
