//
//  ExpandedCardDetailRouter.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 7/20/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ExpandedCardDetailRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ExpandedCardDetailDataPassing {
    var dataStore: ExpandedCardDetailDataStore? { get }
}

class ExpandedCardDetailRouter: NSObject, ExpandedCardDetailRoutingLogic, ExpandedCardDetailDataPassing {
    
    weak var viewController: ExpandedCardDetailViewController?
    var dataStore: ExpandedCardDetailDataStore?
  
    // MARK: Routing


    // MARK: Navigation



    // MARK: Passing data
  
}
