//
//  DeckDetailModels.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/3/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DeckDetail
{
    // MARK: Use cases
    
    enum ShowDeck {
        struct Request {
            
        }
        struct Response {
            let deck: Deck
        }
        enum ViewModel {
            struct DeckInfoModel {
                let displayedDeckName: String
                let displayedDeckID: UUID
            }
            struct DeckCardModels {
                let displayedCards: [DeckDetailCollectionViewCell.CardCellModel]
            }
        }
        
    }
    
    
    enum ShowCreateCard {
        struct Request {
            let displayedDeckID: UUID
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    
    enum CreateCard {
        struct Request {
            let deckID: UUID
            let frontSideText: String
            let backSideText: String
        }
        struct Response {
            let card: Card
        }
        struct ViewModel {
            let displayedCard: DeckDetailCollectionViewCell.CardCellModel
        }
    }
    
    enum ShowEditTitleAlert {
        struct Request {
            let deckID: UUID
        }
        
        struct Response {
            let newDeckTitle: String
        }
        
        struct ViewModel {
            let newDeckTitle: String
        }
    }
    
    
    enum StudyDeck {
        struct Request {
            
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
}


