//
//  DeckDetailRouter.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/3/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DeckDetailRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DeckDetailDataPassing
{
  var dataStore: DeckDetailDataStore? { get }
}

class DeckDetailRouter: NSObject, DeckDetailRoutingLogic, DeckDetailDataPassing
{
    weak var viewController: DeckDetailViewController?
    var dataStore: DeckDetailDataStore?
  
    // MARK: Routing
    
    
    // MARK: Navigation
    
    
    // MARK: Passing data
    
    
}
