//
//  DeckDetailModels.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/3/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DeckDetail
{
    // MARK: Use cases
    
    enum ShowDeck {
        struct Request {
            
        }
        struct Response {
            let deck: NaiveDeck
        }
        enum ViewModel {
            struct DeckInfoModel {
                let displayedDeckName: String
                let displayedDeckID: UUID
            }
            struct DeckCardModels {
                let displayedCards: [DeckDetailCollectionViewCell.CardCellModel]
            }
        }
    }
    
    
    enum ShowDeleteDeckAC {
        struct Request {
            let displayedDeckID: UUID
        }
    }
    
    
    enum DeleteDeck {
        struct Response {
        }
        struct viewModel {
            
        }
    }
    
    
    enum ShowCreateCard {
        struct Request {
            let displayedDeckID: UUID
        }
    }
    
    
    enum CreateCard {
        struct Request {
            let deckID: UUID
            let frontSideText: String
            let backSideText: String
        }
        struct Response {
            let card: NaiveCard
        }
        struct ViewModel {
            let displayedCard: DeckDetailCollectionViewCell.CardCellModel
        }
    }
    
    enum ShowEditCardAC {
        struct Request {
            let deckID: UUID
            // use the indexPath.row int for the card ID for now, maybe attach a
            // UUID to each card in the future as well?
            let cardID: Int
        }
        struct Response {
            let card: NaiveCard
            let cardID: Int
        }
        struct ViewModel {
            let displayedCard: DeckDetailCollectionViewCell.CardCellModel
            let cardID: Int
        }
    }
    
    enum ShowDeleteCardAC {
        struct Request {
            let deckID: UUID
            // indexPath.row for card ID
            let cardID: Int
        }
        struct Response {
            let cardIndexToRemove: Int
        }
        struct ViewModel {
            let cardIndexToRemove: Int
        }
    }
    
    enum ShowEditTitleAlert {
        struct Request {
            let deckID: UUID
        }
        
        struct Response {
            let newDeckTitle: String
        }
        
        struct ViewModel {
            let newDeckTitle: String
        }
    }
    
    
    enum StudyDeck {
        struct Request {
            
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
}


