//
//  DeckDetailInteractor.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/3/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeckDetailBusinessLogic
{
    func getDeck(request: DeckDetail.ShowDeck.Request)
    
    func createCard(request: DeckDetail.CreateCard.Request)
    
    func showCreateCard(request: DeckDetail.ShowCreateCard.Request)
}

protocol DeckDetailDataStore
{
    var deckInfo: Deck? { get set }
}

class DeckDetailInteractor: DeckDetailBusinessLogic, DeckDetailDataStore
{
    var presenter: DeckDetailPresentationLogic?
    var worker: DeckDetailWorker?
    
    var deckInfo: Deck?
  
    // MARK: Do something
    
    func getDeck(request: DeckDetail.ShowDeck.Request) {
        guard let deckInfo = deckInfo else {
            assertionFailure("No deck info available")
            return
        }
        
        let response = DeckDetail.ShowDeck.Response(deck: deckInfo)
        presenter?.presentDeck(response: response)
    }
    
    func createCard(request: DeckDetail.CreateCard.Request) {
//        let response = DeckDetail.CreateCard.Response()
    }
    
    func showCreateCard(request: DeckDetail.ShowCreateCard.Request) {
        let response = DeckDetail.ShowCreateCard.Response()
        presenter?.presentCreateCard(response: response)
    }
    
}

extension DeckDetailInteractor: DeckDetailViewDelegate {
    
    func deckDetailViewSelectStudyDeck(request: DeckDetail.StudyDeck.Request) {
        print("tapped study deck button")
    }
    
}
