//
//  DeckDetailInteractor.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/3/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeckDetailBusinessLogic
{
  func doSomething(request: DeckDetail.Something.Request)
}

protocol DeckDetailDataStore
{
  //var name: String { get set }
}

class DeckDetailInteractor: DeckDetailBusinessLogic, DeckDetailDataStore
{
  var presenter: DeckDetailPresentationLogic?
  var worker: DeckDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: DeckDetail.Something.Request)
  {
    worker = DeckDetailWorker()
    worker?.doSomeWork()
    
    let response = DeckDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
