//
//  DeckDetailPresenter.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/3/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeckDetailPresentationLogic
{
    func presentDeck(response: DeckDetail.ShowDeck.Response)
}

class DeckDetailPresenter: DeckDetailPresentationLogic
{
    weak var viewController: DeckDetailDisplayLogic?
    
    func presentDeck(response: DeckDetail.ShowDeck.Response) {
        let deck = response.deck
        
        let nameOfDeck = deck.nameOfDeck
        let cards = deck.cards
        
        let displayedDeck = DeckDetail.ShowDeck.ViewModel.DisplayedDeck(nameOfDeck: nameOfDeck, cards: cards)
        let viewModel = DeckDetail.ShowDeck.ViewModel(displayedDeck: displayedDeck)
        viewController?.displayDeck(viewModel: viewModel)
    }
}
