//
//  DeckDetailModels.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/3/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DeckDetail
{
  // MARK: Use cases
    
    enum ShowDeck {
        struct Request {
            
        }
        struct Response {
            var deck: Deck
        }
        struct ViewModel {
            struct DisplayedDeck {
                var nameOfDeck: String
                var cards: [Card]
            }
            
            var displayedDeck: DisplayedDeck
        }
    }
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
