//
//  DeckDetailPresenter.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/3/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeckDetailPresentationLogic
{
    func presentDeck(response: DeckDetail.ShowDeck.Response)
    
    func presentCreateCard(response: DeckDetail.ShowCreateCard.Response)
}

class DeckDetailPresenter: DeckDetailPresentationLogic
{
    weak var viewController: DeckDetailDisplayLogic?
    
    func presentDeck(response: DeckDetail.ShowDeck.Response) {
        let deck = response.deck
        
        // name formatting for viewmodel
        let nameOfDeck = deck.nameOfDeck
        let deckNameModel = DeckDetail.ShowDeck.ViewModel.DeckNameModel(displayedDeckName: nameOfDeck)
        viewController?.displayDeckName(viewModel: deckNameModel)
        
        // card formatting for viewmodel
        var cards: [DeckDetailCollectionViewCell.CardCellModel] = []
        
        for card in deck.cards {
            let cellModel = DeckDetailCollectionViewCell.CardCellModel(frontSide: card.frontSide, backSide: card.backSide)
            cards.append(cellModel)
        }
        
        let cardViewModel = DeckDetail.ShowDeck.ViewModel.DeckCardModels(displayedCards: cards)
        viewController?.displayDeckCards(viewModel: cardViewModel)
    }
    
    func presentCreateCard(response: DeckDetail.ShowCreateCard.Response) {
        let acTitle = "Please enter card details"
        let viewModel = DeckDetail.ShowCreateCard.ViewModel(acTitle: acTitle)
        
//        let ac = UIAlertController(title: acTitle, message: nil, preferredStyle: .alert)
        viewController?.displayCreateCard(viewModel: viewModel)
    }
}
