//
//  StudyDeckModels.swift
//  Spaced Repetition
//
//  Created by Kevin Vu on 4/24/20.
//  Copyright (c) 2020 An Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ReviewDeck
{
    // MARK: Use cases
    
    enum ConfigureData {
        struct Request {
        }
        struct Response {
            let firstCardToReview: Card?
            let numOfCardsToReview: Int?
            let nameOfDeckBeingReviewed: String
        }
        struct ViewModel {
            let cardToReviewCardModel: ReviewDeckView.ReviewCardModel
            let numOfCardsToReview: Int?
            let nameOfDeckBeingReviewed: String
        }
    }
    
    enum MoveToNextCard {
        struct Request {
            
        }
        struct Response {
            let nextCardToReview: Card?
        }
        struct ViewModel {
            let cardModelForNextCard: ReviewDeckView.ReviewCardModel
        }
    }
    
    enum FinishedReviewingDeck {
        struct Request {
            
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    enum NoCardsToReview {
        struct Request {
            
        }
        // After the interactor request, response and viewmodel both follow
        // the finishedreviewing deck model
    }
}
